/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as MarcarRouteImport } from './routes/marcar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as PortalPermisosRouteImport } from './routes/portal.permisos'
import { Route as PortalLiquidacionesRouteImport } from './routes/portal.liquidaciones'
import { Route as PortalDocumentosRouteImport } from './routes/portal.documentos'
import { Route as PortalAsistenciaRouteImport } from './routes/portal.asistencia'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as PrintTipoIdRouteImport } from './routes/print.$tipo.$id'
import { Route as AppRrhhVacacionesRouteImport } from './routes/_app/rrhh/vacaciones'
import { Route as AppRrhhLiquidacionesRouteImport } from './routes/_app/rrhh/liquidaciones'
import { Route as AppRrhhHorasExtrasRouteImport } from './routes/_app/rrhh/horas-extras'
import { Route as AppRrhhEmpleadosRouteImport } from './routes/_app/rrhh/empleados'
import { Route as AppRrhhCartasRouteImport } from './routes/_app/rrhh/cartas'
import { Route as AppRrhhAsistenciaRouteImport } from './routes/_app/rrhh/asistencia'
import { Route as AppReclutamientoOfertasRouteImport } from './routes/_app/reclutamiento/ofertas'
import { Route as AppReclutamientoCandidatosRouteImport } from './routes/_app/reclutamiento/candidatos'
import { Route as AppOperacionesTurnosRouteImport } from './routes/_app/operaciones/turnos'
import { Route as AppOperacionesProductividadRouteImport } from './routes/_app/operaciones/productividad'
import { Route as AppMarketplaceServiciosRouteImport } from './routes/_app/marketplace/servicios'
import { Route as AppMarketplaceProveedoresRouteImport } from './routes/_app/marketplace/proveedores'
import { Route as AppMarketingContenidoRouteImport } from './routes/_app/marketing/contenido'
import { Route as AppMarketingCampanasRouteImport } from './routes/_app/marketing/campanas'
import { Route as AppIaPrediccionesRouteImport } from './routes/_app/ia/predicciones'
import { Route as AppIaAlertasRouteImport } from './routes/_app/ia/alertas'
import { Route as AppFinanzasPresupuestoRouteImport } from './routes/_app/finanzas/presupuesto'
import { Route as AppFinanzasIngresosRouteImport } from './routes/_app/finanzas/ingresos'
import { Route as AppFinanzasGastosRouteImport } from './routes/_app/finanzas/gastos'
import { Route as AppFinanzasFlujoCajaRouteImport } from './routes/_app/finanzas/flujo-caja'
import { Route as AppFinanzasDashboardRouteImport } from './routes/_app/finanzas/dashboard'
import { Route as AppFinanzasCostosRouteImport } from './routes/_app/finanzas/costos'
import { Route as AppCumplimientoJornadaRouteImport } from './routes/_app/cumplimiento/jornada'
import { Route as AppCumplimientoDocumentosRouteImport } from './routes/_app/cumplimiento/documentos'
import { Route as AppCumplimientoContratosRouteImport } from './routes/_app/cumplimiento/contratos'
import { Route as AppCumplimientoAlertasRouteImport } from './routes/_app/cumplimiento/alertas'
import { Route as AppConfiguracionEmpresaRouteImport } from './routes/_app/configuracion/empresa'

const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcarRoute = MarcarRouteImport.update({
  id: '/marcar',
  path: '/marcar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalPermisosRoute = PortalPermisosRouteImport.update({
  id: '/permisos',
  path: '/permisos',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLiquidacionesRoute = PortalLiquidacionesRouteImport.update({
  id: '/liquidaciones',
  path: '/liquidaciones',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDocumentosRoute = PortalDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAsistenciaRoute = PortalAsistenciaRouteImport.update({
  id: '/asistencia',
  path: '/asistencia',
  getParentRoute: () => PortalRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const PrintTipoIdRoute = PrintTipoIdRouteImport.update({
  id: '/print/$tipo/$id',
  path: '/print/$tipo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRrhhVacacionesRoute = AppRrhhVacacionesRouteImport.update({
  id: '/rrhh/vacaciones',
  path: '/rrhh/vacaciones',
  getParentRoute: () => AppRoute,
} as any)
const AppRrhhLiquidacionesRoute = AppRrhhLiquidacionesRouteImport.update({
  id: '/rrhh/liquidaciones',
  path: '/rrhh/liquidaciones',
  getParentRoute: () => AppRoute,
} as any)
const AppRrhhHorasExtrasRoute = AppRrhhHorasExtrasRouteImport.update({
  id: '/rrhh/horas-extras',
  path: '/rrhh/horas-extras',
  getParentRoute: () => AppRoute,
} as any)
const AppRrhhEmpleadosRoute = AppRrhhEmpleadosRouteImport.update({
  id: '/rrhh/empleados',
  path: '/rrhh/empleados',
  getParentRoute: () => AppRoute,
} as any)
const AppRrhhCartasRoute = AppRrhhCartasRouteImport.update({
  id: '/rrhh/cartas',
  path: '/rrhh/cartas',
  getParentRoute: () => AppRoute,
} as any)
const AppRrhhAsistenciaRoute = AppRrhhAsistenciaRouteImport.update({
  id: '/rrhh/asistencia',
  path: '/rrhh/asistencia',
  getParentRoute: () => AppRoute,
} as any)
const AppReclutamientoOfertasRoute = AppReclutamientoOfertasRouteImport.update({
  id: '/reclutamiento/ofertas',
  path: '/reclutamiento/ofertas',
  getParentRoute: () => AppRoute,
} as any)
const AppReclutamientoCandidatosRoute =
  AppReclutamientoCandidatosRouteImport.update({
    id: '/reclutamiento/candidatos',
    path: '/reclutamiento/candidatos',
    getParentRoute: () => AppRoute,
  } as any)
const AppOperacionesTurnosRoute = AppOperacionesTurnosRouteImport.update({
  id: '/operaciones/turnos',
  path: '/operaciones/turnos',
  getParentRoute: () => AppRoute,
} as any)
const AppOperacionesProductividadRoute =
  AppOperacionesProductividadRouteImport.update({
    id: '/operaciones/productividad',
    path: '/operaciones/productividad',
    getParentRoute: () => AppRoute,
  } as any)
const AppMarketplaceServiciosRoute = AppMarketplaceServiciosRouteImport.update({
  id: '/marketplace/servicios',
  path: '/marketplace/servicios',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketplaceProveedoresRoute =
  AppMarketplaceProveedoresRouteImport.update({
    id: '/marketplace/proveedores',
    path: '/marketplace/proveedores',
    getParentRoute: () => AppRoute,
  } as any)
const AppMarketingContenidoRoute = AppMarketingContenidoRouteImport.update({
  id: '/marketing/contenido',
  path: '/marketing/contenido',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketingCampanasRoute = AppMarketingCampanasRouteImport.update({
  id: '/marketing/campanas',
  path: '/marketing/campanas',
  getParentRoute: () => AppRoute,
} as any)
const AppIaPrediccionesRoute = AppIaPrediccionesRouteImport.update({
  id: '/ia/predicciones',
  path: '/ia/predicciones',
  getParentRoute: () => AppRoute,
} as any)
const AppIaAlertasRoute = AppIaAlertasRouteImport.update({
  id: '/ia/alertas',
  path: '/ia/alertas',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanzasPresupuestoRoute = AppFinanzasPresupuestoRouteImport.update({
  id: '/finanzas/presupuesto',
  path: '/finanzas/presupuesto',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanzasIngresosRoute = AppFinanzasIngresosRouteImport.update({
  id: '/finanzas/ingresos',
  path: '/finanzas/ingresos',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanzasGastosRoute = AppFinanzasGastosRouteImport.update({
  id: '/finanzas/gastos',
  path: '/finanzas/gastos',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanzasFlujoCajaRoute = AppFinanzasFlujoCajaRouteImport.update({
  id: '/finanzas/flujo-caja',
  path: '/finanzas/flujo-caja',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanzasDashboardRoute = AppFinanzasDashboardRouteImport.update({
  id: '/finanzas/dashboard',
  path: '/finanzas/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanzasCostosRoute = AppFinanzasCostosRouteImport.update({
  id: '/finanzas/costos',
  path: '/finanzas/costos',
  getParentRoute: () => AppRoute,
} as any)
const AppCumplimientoJornadaRoute = AppCumplimientoJornadaRouteImport.update({
  id: '/cumplimiento/jornada',
  path: '/cumplimiento/jornada',
  getParentRoute: () => AppRoute,
} as any)
const AppCumplimientoDocumentosRoute =
  AppCumplimientoDocumentosRouteImport.update({
    id: '/cumplimiento/documentos',
    path: '/cumplimiento/documentos',
    getParentRoute: () => AppRoute,
  } as any)
const AppCumplimientoContratosRoute =
  AppCumplimientoContratosRouteImport.update({
    id: '/cumplimiento/contratos',
    path: '/cumplimiento/contratos',
    getParentRoute: () => AppRoute,
  } as any)
const AppCumplimientoAlertasRoute = AppCumplimientoAlertasRouteImport.update({
  id: '/cumplimiento/alertas',
  path: '/cumplimiento/alertas',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracionEmpresaRoute = AppConfiguracionEmpresaRouteImport.update({
  id: '/configuracion/empresa',
  path: '/configuracion/empresa',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/marcar': typeof MarcarRoute
  '/portal': typeof PortalRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/portal/asistencia': typeof PortalAsistenciaRoute
  '/portal/documentos': typeof PortalDocumentosRoute
  '/portal/liquidaciones': typeof PortalLiquidacionesRoute
  '/portal/permisos': typeof PortalPermisosRoute
  '/configuracion/empresa': typeof AppConfiguracionEmpresaRoute
  '/cumplimiento/alertas': typeof AppCumplimientoAlertasRoute
  '/cumplimiento/contratos': typeof AppCumplimientoContratosRoute
  '/cumplimiento/documentos': typeof AppCumplimientoDocumentosRoute
  '/cumplimiento/jornada': typeof AppCumplimientoJornadaRoute
  '/finanzas/costos': typeof AppFinanzasCostosRoute
  '/finanzas/dashboard': typeof AppFinanzasDashboardRoute
  '/finanzas/flujo-caja': typeof AppFinanzasFlujoCajaRoute
  '/finanzas/gastos': typeof AppFinanzasGastosRoute
  '/finanzas/ingresos': typeof AppFinanzasIngresosRoute
  '/finanzas/presupuesto': typeof AppFinanzasPresupuestoRoute
  '/ia/alertas': typeof AppIaAlertasRoute
  '/ia/predicciones': typeof AppIaPrediccionesRoute
  '/marketing/campanas': typeof AppMarketingCampanasRoute
  '/marketing/contenido': typeof AppMarketingContenidoRoute
  '/marketplace/proveedores': typeof AppMarketplaceProveedoresRoute
  '/marketplace/servicios': typeof AppMarketplaceServiciosRoute
  '/operaciones/productividad': typeof AppOperacionesProductividadRoute
  '/operaciones/turnos': typeof AppOperacionesTurnosRoute
  '/reclutamiento/candidatos': typeof AppReclutamientoCandidatosRoute
  '/reclutamiento/ofertas': typeof AppReclutamientoOfertasRoute
  '/rrhh/asistencia': typeof AppRrhhAsistenciaRoute
  '/rrhh/cartas': typeof AppRrhhCartasRoute
  '/rrhh/empleados': typeof AppRrhhEmpleadosRoute
  '/rrhh/horas-extras': typeof AppRrhhHorasExtrasRoute
  '/rrhh/liquidaciones': typeof AppRrhhLiquidacionesRoute
  '/rrhh/vacaciones': typeof AppRrhhVacacionesRoute
  '/print/$tipo/$id': typeof PrintTipoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/marcar': typeof MarcarRoute
  '/portal': typeof PortalRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/portal/asistencia': typeof PortalAsistenciaRoute
  '/portal/documentos': typeof PortalDocumentosRoute
  '/portal/liquidaciones': typeof PortalLiquidacionesRoute
  '/portal/permisos': typeof PortalPermisosRoute
  '/configuracion/empresa': typeof AppConfiguracionEmpresaRoute
  '/cumplimiento/alertas': typeof AppCumplimientoAlertasRoute
  '/cumplimiento/contratos': typeof AppCumplimientoContratosRoute
  '/cumplimiento/documentos': typeof AppCumplimientoDocumentosRoute
  '/cumplimiento/jornada': typeof AppCumplimientoJornadaRoute
  '/finanzas/costos': typeof AppFinanzasCostosRoute
  '/finanzas/dashboard': typeof AppFinanzasDashboardRoute
  '/finanzas/flujo-caja': typeof AppFinanzasFlujoCajaRoute
  '/finanzas/gastos': typeof AppFinanzasGastosRoute
  '/finanzas/ingresos': typeof AppFinanzasIngresosRoute
  '/finanzas/presupuesto': typeof AppFinanzasPresupuestoRoute
  '/ia/alertas': typeof AppIaAlertasRoute
  '/ia/predicciones': typeof AppIaPrediccionesRoute
  '/marketing/campanas': typeof AppMarketingCampanasRoute
  '/marketing/contenido': typeof AppMarketingContenidoRoute
  '/marketplace/proveedores': typeof AppMarketplaceProveedoresRoute
  '/marketplace/servicios': typeof AppMarketplaceServiciosRoute
  '/operaciones/productividad': typeof AppOperacionesProductividadRoute
  '/operaciones/turnos': typeof AppOperacionesTurnosRoute
  '/reclutamiento/candidatos': typeof AppReclutamientoCandidatosRoute
  '/reclutamiento/ofertas': typeof AppReclutamientoOfertasRoute
  '/rrhh/asistencia': typeof AppRrhhAsistenciaRoute
  '/rrhh/cartas': typeof AppRrhhCartasRoute
  '/rrhh/empleados': typeof AppRrhhEmpleadosRoute
  '/rrhh/horas-extras': typeof AppRrhhHorasExtrasRoute
  '/rrhh/liquidaciones': typeof AppRrhhLiquidacionesRoute
  '/rrhh/vacaciones': typeof AppRrhhVacacionesRoute
  '/print/$tipo/$id': typeof PrintTipoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/marcar': typeof MarcarRoute
  '/portal': typeof PortalRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/portal/asistencia': typeof PortalAsistenciaRoute
  '/portal/documentos': typeof PortalDocumentosRoute
  '/portal/liquidaciones': typeof PortalLiquidacionesRoute
  '/portal/permisos': typeof PortalPermisosRoute
  '/_app/configuracion/empresa': typeof AppConfiguracionEmpresaRoute
  '/_app/cumplimiento/alertas': typeof AppCumplimientoAlertasRoute
  '/_app/cumplimiento/contratos': typeof AppCumplimientoContratosRoute
  '/_app/cumplimiento/documentos': typeof AppCumplimientoDocumentosRoute
  '/_app/cumplimiento/jornada': typeof AppCumplimientoJornadaRoute
  '/_app/finanzas/costos': typeof AppFinanzasCostosRoute
  '/_app/finanzas/dashboard': typeof AppFinanzasDashboardRoute
  '/_app/finanzas/flujo-caja': typeof AppFinanzasFlujoCajaRoute
  '/_app/finanzas/gastos': typeof AppFinanzasGastosRoute
  '/_app/finanzas/ingresos': typeof AppFinanzasIngresosRoute
  '/_app/finanzas/presupuesto': typeof AppFinanzasPresupuestoRoute
  '/_app/ia/alertas': typeof AppIaAlertasRoute
  '/_app/ia/predicciones': typeof AppIaPrediccionesRoute
  '/_app/marketing/campanas': typeof AppMarketingCampanasRoute
  '/_app/marketing/contenido': typeof AppMarketingContenidoRoute
  '/_app/marketplace/proveedores': typeof AppMarketplaceProveedoresRoute
  '/_app/marketplace/servicios': typeof AppMarketplaceServiciosRoute
  '/_app/operaciones/productividad': typeof AppOperacionesProductividadRoute
  '/_app/operaciones/turnos': typeof AppOperacionesTurnosRoute
  '/_app/reclutamiento/candidatos': typeof AppReclutamientoCandidatosRoute
  '/_app/reclutamiento/ofertas': typeof AppReclutamientoOfertasRoute
  '/_app/rrhh/asistencia': typeof AppRrhhAsistenciaRoute
  '/_app/rrhh/cartas': typeof AppRrhhCartasRoute
  '/_app/rrhh/empleados': typeof AppRrhhEmpleadosRoute
  '/_app/rrhh/horas-extras': typeof AppRrhhHorasExtrasRoute
  '/_app/rrhh/liquidaciones': typeof AppRrhhLiquidacionesRoute
  '/_app/rrhh/vacaciones': typeof AppRrhhVacacionesRoute
  '/print/$tipo/$id': typeof PrintTipoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/marcar'
    | '/portal'
    | '/dashboard'
    | '/portal/asistencia'
    | '/portal/documentos'
    | '/portal/liquidaciones'
    | '/portal/permisos'
    | '/configuracion/empresa'
    | '/cumplimiento/alertas'
    | '/cumplimiento/contratos'
    | '/cumplimiento/documentos'
    | '/cumplimiento/jornada'
    | '/finanzas/costos'
    | '/finanzas/dashboard'
    | '/finanzas/flujo-caja'
    | '/finanzas/gastos'
    | '/finanzas/ingresos'
    | '/finanzas/presupuesto'
    | '/ia/alertas'
    | '/ia/predicciones'
    | '/marketing/campanas'
    | '/marketing/contenido'
    | '/marketplace/proveedores'
    | '/marketplace/servicios'
    | '/operaciones/productividad'
    | '/operaciones/turnos'
    | '/reclutamiento/candidatos'
    | '/reclutamiento/ofertas'
    | '/rrhh/asistencia'
    | '/rrhh/cartas'
    | '/rrhh/empleados'
    | '/rrhh/horas-extras'
    | '/rrhh/liquidaciones'
    | '/rrhh/vacaciones'
    | '/print/$tipo/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/marcar'
    | '/portal'
    | '/dashboard'
    | '/portal/asistencia'
    | '/portal/documentos'
    | '/portal/liquidaciones'
    | '/portal/permisos'
    | '/configuracion/empresa'
    | '/cumplimiento/alertas'
    | '/cumplimiento/contratos'
    | '/cumplimiento/documentos'
    | '/cumplimiento/jornada'
    | '/finanzas/costos'
    | '/finanzas/dashboard'
    | '/finanzas/flujo-caja'
    | '/finanzas/gastos'
    | '/finanzas/ingresos'
    | '/finanzas/presupuesto'
    | '/ia/alertas'
    | '/ia/predicciones'
    | '/marketing/campanas'
    | '/marketing/contenido'
    | '/marketplace/proveedores'
    | '/marketplace/servicios'
    | '/operaciones/productividad'
    | '/operaciones/turnos'
    | '/reclutamiento/candidatos'
    | '/reclutamiento/ofertas'
    | '/rrhh/asistencia'
    | '/rrhh/cartas'
    | '/rrhh/empleados'
    | '/rrhh/horas-extras'
    | '/rrhh/liquidaciones'
    | '/rrhh/vacaciones'
    | '/print/$tipo/$id'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/marcar'
    | '/portal'
    | '/_app/dashboard'
    | '/portal/asistencia'
    | '/portal/documentos'
    | '/portal/liquidaciones'
    | '/portal/permisos'
    | '/_app/configuracion/empresa'
    | '/_app/cumplimiento/alertas'
    | '/_app/cumplimiento/contratos'
    | '/_app/cumplimiento/documentos'
    | '/_app/cumplimiento/jornada'
    | '/_app/finanzas/costos'
    | '/_app/finanzas/dashboard'
    | '/_app/finanzas/flujo-caja'
    | '/_app/finanzas/gastos'
    | '/_app/finanzas/ingresos'
    | '/_app/finanzas/presupuesto'
    | '/_app/ia/alertas'
    | '/_app/ia/predicciones'
    | '/_app/marketing/campanas'
    | '/_app/marketing/contenido'
    | '/_app/marketplace/proveedores'
    | '/_app/marketplace/servicios'
    | '/_app/operaciones/productividad'
    | '/_app/operaciones/turnos'
    | '/_app/reclutamiento/candidatos'
    | '/_app/reclutamiento/ofertas'
    | '/_app/rrhh/asistencia'
    | '/_app/rrhh/cartas'
    | '/_app/rrhh/empleados'
    | '/_app/rrhh/horas-extras'
    | '/_app/rrhh/liquidaciones'
    | '/_app/rrhh/vacaciones'
    | '/print/$tipo/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  MarcarRoute: typeof MarcarRoute
  PortalRoute: typeof PortalRouteWithChildren
  PrintTipoIdRoute: typeof PrintTipoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marcar': {
      id: '/marcar'
      path: '/marcar'
      fullPath: '/marcar'
      preLoaderRoute: typeof MarcarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/permisos': {
      id: '/portal/permisos'
      path: '/permisos'
      fullPath: '/portal/permisos'
      preLoaderRoute: typeof PortalPermisosRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/liquidaciones': {
      id: '/portal/liquidaciones'
      path: '/liquidaciones'
      fullPath: '/portal/liquidaciones'
      preLoaderRoute: typeof PortalLiquidacionesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/documentos': {
      id: '/portal/documentos'
      path: '/documentos'
      fullPath: '/portal/documentos'
      preLoaderRoute: typeof PortalDocumentosRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/asistencia': {
      id: '/portal/asistencia'
      path: '/asistencia'
      fullPath: '/portal/asistencia'
      preLoaderRoute: typeof PortalAsistenciaRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/print/$tipo/$id': {
      id: '/print/$tipo/$id'
      path: '/print/$tipo/$id'
      fullPath: '/print/$tipo/$id'
      preLoaderRoute: typeof PrintTipoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/rrhh/vacaciones': {
      id: '/_app/rrhh/vacaciones'
      path: '/rrhh/vacaciones'
      fullPath: '/rrhh/vacaciones'
      preLoaderRoute: typeof AppRrhhVacacionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rrhh/liquidaciones': {
      id: '/_app/rrhh/liquidaciones'
      path: '/rrhh/liquidaciones'
      fullPath: '/rrhh/liquidaciones'
      preLoaderRoute: typeof AppRrhhLiquidacionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rrhh/horas-extras': {
      id: '/_app/rrhh/horas-extras'
      path: '/rrhh/horas-extras'
      fullPath: '/rrhh/horas-extras'
      preLoaderRoute: typeof AppRrhhHorasExtrasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rrhh/empleados': {
      id: '/_app/rrhh/empleados'
      path: '/rrhh/empleados'
      fullPath: '/rrhh/empleados'
      preLoaderRoute: typeof AppRrhhEmpleadosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rrhh/cartas': {
      id: '/_app/rrhh/cartas'
      path: '/rrhh/cartas'
      fullPath: '/rrhh/cartas'
      preLoaderRoute: typeof AppRrhhCartasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rrhh/asistencia': {
      id: '/_app/rrhh/asistencia'
      path: '/rrhh/asistencia'
      fullPath: '/rrhh/asistencia'
      preLoaderRoute: typeof AppRrhhAsistenciaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reclutamiento/ofertas': {
      id: '/_app/reclutamiento/ofertas'
      path: '/reclutamiento/ofertas'
      fullPath: '/reclutamiento/ofertas'
      preLoaderRoute: typeof AppReclutamientoOfertasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reclutamiento/candidatos': {
      id: '/_app/reclutamiento/candidatos'
      path: '/reclutamiento/candidatos'
      fullPath: '/reclutamiento/candidatos'
      preLoaderRoute: typeof AppReclutamientoCandidatosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/operaciones/turnos': {
      id: '/_app/operaciones/turnos'
      path: '/operaciones/turnos'
      fullPath: '/operaciones/turnos'
      preLoaderRoute: typeof AppOperacionesTurnosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/operaciones/productividad': {
      id: '/_app/operaciones/productividad'
      path: '/operaciones/productividad'
      fullPath: '/operaciones/productividad'
      preLoaderRoute: typeof AppOperacionesProductividadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketplace/servicios': {
      id: '/_app/marketplace/servicios'
      path: '/marketplace/servicios'
      fullPath: '/marketplace/servicios'
      preLoaderRoute: typeof AppMarketplaceServiciosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketplace/proveedores': {
      id: '/_app/marketplace/proveedores'
      path: '/marketplace/proveedores'
      fullPath: '/marketplace/proveedores'
      preLoaderRoute: typeof AppMarketplaceProveedoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketing/contenido': {
      id: '/_app/marketing/contenido'
      path: '/marketing/contenido'
      fullPath: '/marketing/contenido'
      preLoaderRoute: typeof AppMarketingContenidoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketing/campanas': {
      id: '/_app/marketing/campanas'
      path: '/marketing/campanas'
      fullPath: '/marketing/campanas'
      preLoaderRoute: typeof AppMarketingCampanasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ia/predicciones': {
      id: '/_app/ia/predicciones'
      path: '/ia/predicciones'
      fullPath: '/ia/predicciones'
      preLoaderRoute: typeof AppIaPrediccionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ia/alertas': {
      id: '/_app/ia/alertas'
      path: '/ia/alertas'
      fullPath: '/ia/alertas'
      preLoaderRoute: typeof AppIaAlertasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finanzas/presupuesto': {
      id: '/_app/finanzas/presupuesto'
      path: '/finanzas/presupuesto'
      fullPath: '/finanzas/presupuesto'
      preLoaderRoute: typeof AppFinanzasPresupuestoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finanzas/ingresos': {
      id: '/_app/finanzas/ingresos'
      path: '/finanzas/ingresos'
      fullPath: '/finanzas/ingresos'
      preLoaderRoute: typeof AppFinanzasIngresosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finanzas/gastos': {
      id: '/_app/finanzas/gastos'
      path: '/finanzas/gastos'
      fullPath: '/finanzas/gastos'
      preLoaderRoute: typeof AppFinanzasGastosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finanzas/flujo-caja': {
      id: '/_app/finanzas/flujo-caja'
      path: '/finanzas/flujo-caja'
      fullPath: '/finanzas/flujo-caja'
      preLoaderRoute: typeof AppFinanzasFlujoCajaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finanzas/dashboard': {
      id: '/_app/finanzas/dashboard'
      path: '/finanzas/dashboard'
      fullPath: '/finanzas/dashboard'
      preLoaderRoute: typeof AppFinanzasDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finanzas/costos': {
      id: '/_app/finanzas/costos'
      path: '/finanzas/costos'
      fullPath: '/finanzas/costos'
      preLoaderRoute: typeof AppFinanzasCostosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cumplimiento/jornada': {
      id: '/_app/cumplimiento/jornada'
      path: '/cumplimiento/jornada'
      fullPath: '/cumplimiento/jornada'
      preLoaderRoute: typeof AppCumplimientoJornadaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cumplimiento/documentos': {
      id: '/_app/cumplimiento/documentos'
      path: '/cumplimiento/documentos'
      fullPath: '/cumplimiento/documentos'
      preLoaderRoute: typeof AppCumplimientoDocumentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cumplimiento/contratos': {
      id: '/_app/cumplimiento/contratos'
      path: '/cumplimiento/contratos'
      fullPath: '/cumplimiento/contratos'
      preLoaderRoute: typeof AppCumplimientoContratosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cumplimiento/alertas': {
      id: '/_app/cumplimiento/alertas'
      path: '/cumplimiento/alertas'
      fullPath: '/cumplimiento/alertas'
      preLoaderRoute: typeof AppCumplimientoAlertasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracion/empresa': {
      id: '/_app/configuracion/empresa'
      path: '/configuracion/empresa'
      fullPath: '/configuracion/empresa'
      preLoaderRoute: typeof AppConfiguracionEmpresaRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppConfiguracionEmpresaRoute: typeof AppConfiguracionEmpresaRoute
  AppCumplimientoAlertasRoute: typeof AppCumplimientoAlertasRoute
  AppCumplimientoContratosRoute: typeof AppCumplimientoContratosRoute
  AppCumplimientoDocumentosRoute: typeof AppCumplimientoDocumentosRoute
  AppCumplimientoJornadaRoute: typeof AppCumplimientoJornadaRoute
  AppFinanzasCostosRoute: typeof AppFinanzasCostosRoute
  AppFinanzasDashboardRoute: typeof AppFinanzasDashboardRoute
  AppFinanzasFlujoCajaRoute: typeof AppFinanzasFlujoCajaRoute
  AppFinanzasGastosRoute: typeof AppFinanzasGastosRoute
  AppFinanzasIngresosRoute: typeof AppFinanzasIngresosRoute
  AppFinanzasPresupuestoRoute: typeof AppFinanzasPresupuestoRoute
  AppIaAlertasRoute: typeof AppIaAlertasRoute
  AppIaPrediccionesRoute: typeof AppIaPrediccionesRoute
  AppMarketingCampanasRoute: typeof AppMarketingCampanasRoute
  AppMarketingContenidoRoute: typeof AppMarketingContenidoRoute
  AppMarketplaceProveedoresRoute: typeof AppMarketplaceProveedoresRoute
  AppMarketplaceServiciosRoute: typeof AppMarketplaceServiciosRoute
  AppOperacionesProductividadRoute: typeof AppOperacionesProductividadRoute
  AppOperacionesTurnosRoute: typeof AppOperacionesTurnosRoute
  AppReclutamientoCandidatosRoute: typeof AppReclutamientoCandidatosRoute
  AppReclutamientoOfertasRoute: typeof AppReclutamientoOfertasRoute
  AppRrhhAsistenciaRoute: typeof AppRrhhAsistenciaRoute
  AppRrhhCartasRoute: typeof AppRrhhCartasRoute
  AppRrhhEmpleadosRoute: typeof AppRrhhEmpleadosRoute
  AppRrhhHorasExtrasRoute: typeof AppRrhhHorasExtrasRoute
  AppRrhhLiquidacionesRoute: typeof AppRrhhLiquidacionesRoute
  AppRrhhVacacionesRoute: typeof AppRrhhVacacionesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppConfiguracionEmpresaRoute: AppConfiguracionEmpresaRoute,
  AppCumplimientoAlertasRoute: AppCumplimientoAlertasRoute,
  AppCumplimientoContratosRoute: AppCumplimientoContratosRoute,
  AppCumplimientoDocumentosRoute: AppCumplimientoDocumentosRoute,
  AppCumplimientoJornadaRoute: AppCumplimientoJornadaRoute,
  AppFinanzasCostosRoute: AppFinanzasCostosRoute,
  AppFinanzasDashboardRoute: AppFinanzasDashboardRoute,
  AppFinanzasFlujoCajaRoute: AppFinanzasFlujoCajaRoute,
  AppFinanzasGastosRoute: AppFinanzasGastosRoute,
  AppFinanzasIngresosRoute: AppFinanzasIngresosRoute,
  AppFinanzasPresupuestoRoute: AppFinanzasPresupuestoRoute,
  AppIaAlertasRoute: AppIaAlertasRoute,
  AppIaPrediccionesRoute: AppIaPrediccionesRoute,
  AppMarketingCampanasRoute: AppMarketingCampanasRoute,
  AppMarketingContenidoRoute: AppMarketingContenidoRoute,
  AppMarketplaceProveedoresRoute: AppMarketplaceProveedoresRoute,
  AppMarketplaceServiciosRoute: AppMarketplaceServiciosRoute,
  AppOperacionesProductividadRoute: AppOperacionesProductividadRoute,
  AppOperacionesTurnosRoute: AppOperacionesTurnosRoute,
  AppReclutamientoCandidatosRoute: AppReclutamientoCandidatosRoute,
  AppReclutamientoOfertasRoute: AppReclutamientoOfertasRoute,
  AppRrhhAsistenciaRoute: AppRrhhAsistenciaRoute,
  AppRrhhCartasRoute: AppRrhhCartasRoute,
  AppRrhhEmpleadosRoute: AppRrhhEmpleadosRoute,
  AppRrhhHorasExtrasRoute: AppRrhhHorasExtrasRoute,
  AppRrhhLiquidacionesRoute: AppRrhhLiquidacionesRoute,
  AppRrhhVacacionesRoute: AppRrhhVacacionesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PortalRouteChildren {
  PortalAsistenciaRoute: typeof PortalAsistenciaRoute
  PortalDocumentosRoute: typeof PortalDocumentosRoute
  PortalLiquidacionesRoute: typeof PortalLiquidacionesRoute
  PortalPermisosRoute: typeof PortalPermisosRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAsistenciaRoute: PortalAsistenciaRoute,
  PortalDocumentosRoute: PortalDocumentosRoute,
  PortalLiquidacionesRoute: PortalLiquidacionesRoute,
  PortalPermisosRoute: PortalPermisosRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  MarcarRoute: MarcarRoute,
  PortalRoute: PortalRouteWithChildren,
  PrintTipoIdRoute: PrintTipoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
